name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

         
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          cache: true

      - name: Configure
        working-directory: client
        run: cmake --preset windows-msvc

      - name: Build
        working-directory: client
        run: cmake --build --preset windows-msvc-release

      - name: Install
        working-directory: client
        run: cmake --install build/windows-msvc --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PhotoDB-windows
          path: install/client/windows-msvc/**
